In [1]:
vetor = [1, 2, 3]

In [2]:
vetor[0]

1

In [3]:
matriz = [ [1, 2, 3], [4, 5, 6] ]

In [4]:
matriz

[[1, 2, 3], [4, 5, 6]]

In [5]:
matriz[1][1]

5

In [6]:
matriz = [[0] * 6 for i in range(6)]

In [7]:
matriz

[[0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0]]

In [8]:
for i in range(6):
  for j in range(6):
    matriz[i][j] = 0
    print(i, j)

0 0
0 1
0 2
0 3
0 4
0 5
1 0
1 1
1 2
1 3
1 4
1 5
2 0
2 1
2 2
2 3
2 4
2 5
3 0
3 1
3 2
3 3
3 4
3 5
4 0
4 1
4 2
4 3
4 4
4 5
5 0
5 1
5 2
5 3
5 4
5 5


In [9]:
matriz

[[0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0]]

In [10]:
for l in range(6):
  for c in range(6):
    matriz[l][c] = 10 * l + c 
    print(l, c, 10 * l + c )

0 0 0
0 1 1
0 2 2
0 3 3
0 4 4
0 5 5
1 0 10
1 1 11
1 2 12
1 3 13
1 4 14
1 5 15
2 0 20
2 1 21
2 2 22
2 3 23
2 4 24
2 5 25
3 0 30
3 1 31
3 2 32
3 3 33
3 4 34
3 5 35
4 0 40
4 1 41
4 2 42
4 3 43
4 4 44
4 5 45
5 0 50
5 1 51
5 2 52
5 3 53
5 4 54
5 5 55


In [11]:
matriz

[[0, 1, 2, 3, 4, 5],
 [10, 11, 12, 13, 14, 15],
 [20, 21, 22, 23, 24, 25],
 [30, 31, 32, 33, 34, 35],
 [40, 41, 42, 43, 44, 45],
 [50, 51, 52, 53, 54, 55]]

In [12]:
import numpy as np

In [20]:
a = np.array([1, 2, 3])

In [21]:
print(type(a))

<class 'numpy.ndarray'>


In [22]:
print(a.shape)

(3,)


In [23]:
print(a[0], a[1], a[2])

1 2 3


In [24]:
a

array([1, 2, 3])

In [25]:
a[0] = 5

In [26]:
print(a)

[5 2 3]


In [27]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [28]:
print(b.shape)

(2, 3)


In [29]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


In [30]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [31]:
b = np.ones((1, 2))
print(b)

[[1. 1.]]


In [32]:
c = np.full((2, 2), 7)
print(c)

[[7 7]
 [7 7]]


In [34]:
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
e = np.random.random((2,2))
print(e)

[[0.93479713 0.40463363]
 [0.9529881  0.41990048]]


In [36]:
matriz2 = np.zeros((6,6))


In [37]:
matriz2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [38]:
type(matriz2)

numpy.ndarray

In [39]:
for l in range(6):
  for c in range(6):
    matriz2[l][c] = 10 * l + c 

In [40]:
matriz2

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])

In [41]:
matriz2[0,3:5]

array([3., 4.])

In [42]:
matriz2[4:,4:]

array([[44., 45.],
       [54., 55.]])

In [43]:
matriz2[:,2]

array([ 2., 12., 22., 32., 42., 52.])

In [48]:
matriz2[2::2,0::2]

array([[20., 22., 24.],
       [40., 42., 44.]])

In [49]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
b = a[0:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [51]:
print(a[0, 1])

2


In [52]:
b[0, 0] = 77

In [53]:
print(b)

[[77  3]
 [ 6  7]]


In [54]:
print(a)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
c = a.copy()

In [56]:
print(c)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
c[0][0] = 100

In [58]:
print(a)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [59]:
print(c)

[[100  77   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [60]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])


[1 4 5]


In [61]:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]


In [62]:
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


In [63]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [64]:
x

array([[1., 2.],
       [3., 4.]])

In [65]:
y

array([[5., 6.],
       [7., 8.]])

In [66]:
x * y

array([[ 5., 12.],
       [21., 32.]])

In [67]:
x.dot(y)

array([[19., 22.],
       [43., 50.]])

In [69]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [74]:
x = np.array([ [1,2], 
               [3,4] ])

In [75]:
np.sum(x)

10

In [76]:
np.sum(x, axis=0)

array([4, 6])

In [77]:
np.sum(x, axis=1)

array([3, 7])

In [78]:
x.T

array([[1, 3],
       [2, 4]])